[package]
name = "prototype"
version = "0.1.0"
authors = ["Mike Murphy <codermurph@sleepymurph.com>"]

[lib]
name = "prototype"
path = "src/lib.rs"

[[bin]]
name = "prototype"
path = "src/main.rs"

[dependencies]
clap = "2"
rust-crypto = "0.2"
